#!/usr/bin/perl
use Getopt::Long;
my $contact="Nima Rafati nimarafati\@gmail.com
20180122	";
my $usage = "$0.pl -F freq.file
this script finds the MAF from freq file generated by vcftools (vcftools --vcf ASA_joincalled.recal_snp.recode.vcf --freq --out ASA_joincalled.recal_snp)
$contact\n";

&GetOptions('h=s' =>\$helpFlag,
'F=s' =>\$inputFile);
if($helpFlag || @ARGV eq "")
{
	print $usage;
	exit;
}

my @lineArr=();
my $cntr=0;
open(inF1,$inputFile);# || die print $usage;
while(<inF1>)
{
	$cntr++;
	chomp($_);
	@lineArr=split("\t",$_);
	if($cntr==0)
	{
		print "$_\tMAA\tMAF\n";
	}
	if ($cntr>=1 && $lineArr[0] ne "CHROM")
	{
		$maf=1;
		$maa="";
		chomp($_);
		print "$lineArr[0]\t$lineArr[1]\t$lineArr[2]\t$lineArr[3]\t";
		for ($i=4;$i<scalar(@lineArr);$i++)
		{
			$lineArr[$i]=~ m/(.*):(.*)/;
			$allele=$1;
			$freq=$2;
			if($allele ne "*")
			{
				if($freq<=$maf)
				{
					$maf=$freq;
					$maa=$allele;
#					print "$lineArr[$i]\t$allele:$freq==>$maf";<STDIN>;
				}
#				$snpHash{$allele}=$freq
			}
			$allele="";
			$freq="";
			print "$lineArr[$i];";
		}
		print "\t$maa\t$maf\n";
	}
}
close inF1;
